### PR TITLE
Move Demo 3, update content

### PR DESCRIPTION
**Pull request by jules2689**
Demos were scheduled for the first time this term. As such, my scheduling was a bit off.

This moves back Demo 3 from March 11 to March 25.

I think you should have the app launched sooner than the Demo 3 so this PR changes Demo 3 to talk more about the technical problems you are solving at that time.

Lastly, Demo 4 will be just to the teaching staff as it's your full software :)

### CODE REVIEW

**Review by helloxinw — APPROVED** [review]

**Review by quinte22 — APPROVED** [review]

**Comment by jules2689** [comment]
Hey @MultiW @quinte22 I moved the wrong demo. Tomorrow's is still on, I meant to move March 11's

**Review by helloxinw — APPROVED** [review]

**Review by niktill — APPROVED** [review]
LGTM <3

**Review by kevlie — APPROVED** [review]
LGTM!

**Review by ulmerf — APPROVED** [review]

**Review by JohnGiorgi — APPROVED** [review]

**Review by matthewtory — APPROVED** [review]

**Review by DCastaban — APPROVED** [review]

**Review by yuchenWYC — APPROVED** [review]

**Review by Arieski — APPROVED** [review]

**Review by quinte22 — APPROVED** [review]
👍🏻

**Review by YucenZ — APPROVED** [review]
Thank you!

**Review by JasmineSun33 — APPROVED** [review]

**Pull request merged**
