### PR TITLE
Clarify final demo requirements

### PR DESCRIPTION
**Pull request by jules2689**
What this is
---
During the first lecture, I realized that the final demo was not very clear in what was actually required. It specified `real working software`, but I never divulged what that actually meant.

In order to keep expectations transparent, I am adding a detailed section to describe what this means.

High Level Tl;Dr
---

At a high level it means:

- The application runs
  - It has some design system to help keep consistency (I'm not too worried about how it looks right now, but try to use a pre-made system if you're not design-inclined)
- It is running in production _somewhere_ other than your laptop, unless you are building mobile. desktop, or similar software of course
  - You have logging, exception tracking, etc as allowed by your app
- There is CI setup on a working test suite and linting
- There are scripts aimed to help you get started on the project in one command
- There is a YAML file in the root of the repo that describes some high level requirements, links, and scripts
- The README had been kept up to date

[This is the new assignment rendered](https://github.com/dcsil/CSC491/blob/7db6f3ddd0fdfa8aa60656d33498a4bea3daa2b2/assignments/final_demo.md)

To merge this
---

As this is a modification to an assignment during the term, I require at least 50% of the class (7+) approving this pull request. I have requested the class's input on this, but keep in mind this is a clarification of requirements rather than a change of assignment.

(edit: removed a poorly worded sentence, you can see the edit history by clicking "edited" in the body header)

The intentions here are to consolidate some best practices into the term. I understand you won't have had tons of experience with this all, but I have and we will have a lot of time to work in class. I can guide you through the steps as required then ✨

### CODE REVIEW

**Comment by DanielChanJA** [comment]
Haha I realized I don't have write access, but everything seems clearly outlined and well defined.

**Comment by jules2689** [comment]
@DanielChanJA Thanks for the quick response 🎉 💖 

> Haha I realized I don't have write access

That is intended because it is the syllabus to the course. University policy means I have the last say in what does and doesn't go in... THAT SAID, I highly encourage everyone to participate and propose changes to things as they see fit.

Especially since I need another 6 👍s on this to merge 🙃

**Comment by EndBird** [comment]
You say these requirements will be used regardless but you also you require 50% approval. Seems contradictory.

**Comment by jules2689** [comment]
@EndBird 

> You say these requirements will be used regardless but you also you require 50% approval. Seems contradictory.

You are right. I can appreciate that is how I presented it. This is a result of me forgetting to push this before class started 😓  Sorry about that.

These were the requirements that were implied by `real working software` and the lectures planned for the course. As such, I intended to mark based on these areas but realized I never clarified that for you or the course - which is totally not cool on my part.

I suspect I'll find issues like this in some of the other assignments as we approach them and the class have questions.

#### As for the changes here...

Do you feel the requirements are too difficult? Are they too much work? I intended to outline them with software best practices in what I'd expect from a real software project in a real company. I recognize that not everyone uses the same measure or best practices, so these are simply based on my experiences in infrastructure, SRE (site reliability + operations), devops, and product development.

I'm happy to discuss this in person too. I also recognize some of this is probably new for everyone, so I intend to guide you during the term using our work-in-class portions 🙏

**Comment by EndBird** [comment]
It seems pretty doable! I definitely am totally clueless of some of the terms involved. I have no clue what a design system is...

**Comment by EndBird** [comment]
This sounds trivial but im not sure how one would test our script/bootstrap command. I suppose one could use a lab computer that is totally free of previous installations to test?

**Comment by jules2689** [comment]
Ah, that is good feedback. While it is possible to test a bootstrap script (I'll talk about this, it's a cool topic!) I am not expecting you to have that tested. It is a very hard thing to do and took until thousands of employees to get that going.

I'll clarify what should be tested!

**Pull request merged**
